# -*- coding: utf-8 -*-
"""Makanan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTkJJ-FMbybrBbf2cfhpPeFXq_LNgbGf
"""

import pandas as pd

# Baca File
file_path = '/content/drive/MyDrive/Dataset/nutrition.csv'
df = pd.read_csv(file_path)
df.head()
df.columns
df.info()

def rekomendasi_makanan(mood, lapar, waktu, df, jumlah=5):
    hasil = df.copy()

    # Mood ke nutrisi
    if mood == 'lelah':
        hasil = hasil.sort_values(by=['calories', 'carbohydrate'], ascending=False)
    elif mood == 'sedih':
        hasil = hasil.sort_values(by='carbohydrate', ascending=False)
    elif mood == 'ingin fokus':
        hasil = hasil.sort_values(by='proteins', ascending=False)
    elif mood == 'diet':
        hasil = hasil[(hasil['fat'] < 10) & (hasil['calories'] < 250)]

    # Tingkat lapar
    if lapar == 'sangat lapar':
        hasil = hasil[hasil['calories'] > 300]
    elif lapar == 'ringan':
        hasil = hasil[hasil['calories'] < 250]

    # Waktu makan
    if waktu == 'sarapan':
        hasil = hasil[hasil['carbohydrate'] > 20]
    elif waktu == 'makan siang':
        hasil = hasil[(hasil['calories'] >= 300) & (hasil['calories'] <= 600)]
    elif waktu == 'makan malam':
        hasil = hasil[(hasil['fat'] < 15) & (hasil['calories'] < 500)]

    return hasil.head(jumlah)

import streamlit as st

st.title("🍽️ Sistem Rekomendasi Makanan Berdasarkan Mood")

st.subheader("Masukkan Kondisi Anda:")

# Form input
with st.form("input_form"):
    mood = st.selectbox("Mood Anda", ['lelah', 'sedih', 'ingin fokus', 'diet'])
    lapar = st.selectbox("Tingkat Lapar", ['sangat lapar', 'sedang', 'ringan'])
    waktu = st.selectbox("Waktu Makan", ['sarapan', 'makan siang', 'makan malam'])
    submitted = st.form_submit_button("Tampilkan Rekomendasi")

# Tampilkan hasil jika tombol ditekan
if submitted:
    hasil = rekomendasi_makanan(mood, lapar, waktu, df)

    st.subheader("🍱 Rekomendasi Makanan untuk Anda:")
    if hasil.empty:
        st.warning("Maaf, tidak ada rekomendasi yang cocok. Coba kombinasi lain.")
    else:
        for _, row in hasil.iterrows():
            st.markdown(f"### {row['name']}")
            st.image(row['image'], width=300)
            st.markdown(f"**Kalori:** {row['calories']} kcal")
            st.markdown(f"**Protein:** {row['proteins']} g")
            st.markdown(f"**Lemak:** {row['fat']} g")
            st.markdown(f"**Karbohidrat:** {row['carbohydrate']} g")
            st.markdown("---")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# streamlit
# pandas
